title: Thinkers CSA Repository
description: "We are the thinkers!"
owner_name: Yash Parikh
github_username: illuminati1618 
github_repo: "pages-thinkers-yash" 
baseurl: "/pages-thinkers-yash/" 
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/illuminati1618/pages-thinkers-yash" }
    - { platform: x, user_url: "https://x.com/Open_Coding" }
    - { platform: youtube, user_url: "https://www.youtube.com/@OpenCodingSociety" } 
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

header_pages:
  - navigation/section/csse.md
  - navigation/section/csp.md
  - navigation/section/csa.md 
  - navigation/blog.md
  - navigation/search.md
  - navigation/logintoolkit.md
